$(function(){
//	var goodslist1 = new GoodsList({
//		renderTo:"goodsList1",
//		dataSource:[{
//			id:1,
//			name:"AirPods",
//			price:"1276"
//		},{
//			id:2,
//			name:"Beats Solo3 Wireless 头戴式耳机 - 哑光黑色",
//			price:"2,268"
//		},{
//			id:3,
//			name:"Powerbeats3 Wireless 入耳式耳机 - Beats Decade Collection - 桀骜黑红",
//			price:"1,475"
//		},{
//			id:4,
//			name:"Wahoo ELEMNT GPS 骑行电脑",
//			price:"2,774"
//		},{
//			id:5,
//			name:"iPhone 8 Plus/7 Plus 硅胶保护壳 - 碧海色",
//			price:"325"
//		},{
//			id:6,
//			name:"Belkin Boost Up Wireless Charging Pad",
//			price:"398"
//		},{
//			id:7,
//			name:"闪电转 30 针转换器",
//			price:"226"
//		},{
//			id:8,
//			name:"iPhone 闪电基座 – 金色",
//			price:"424"
//		},{
//			id:9,
//			name:"Belkin InvisiGlass Ultra 屏幕保护膜 (适用于 iPhone X)",
//			price:"325"
//		},{
//			id:10,
//			name:"DJI 灵眸 OSMO 手机云台 2 (适用于 iPhone)",
//			price:"890"
//		},{
//			id:11,
//			name:"Belkin Valet 充电底座 (适用于 iPhone 和 Apple Watch)",
//			price:"890"
//		},{
//			id:12,
//			name:"Incase Nylon 配件收纳包 (适用于 iPhone 和 Apple Watch)",
//			price:"375"
//		}],
//		onComplete:function(){
//			for ( var i = 0; i < $(".data-suju-gl-imgpanel","#goodsList1").length; i++) {
//				new slideshow({
//					renderTo:"data-suju-gl-imgpanel"+i,
//					dataSource:[{
//						goodsId:1,
//						imgList:[{
//							index:1,
//							img:"img/good/goods1_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods1_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods1_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:2,
//						imgList:[{
//							index:1,
//							img:"img/good/goods2_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods2_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods2_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:3,
//						imgList:[{
//							index:1,
//							img:"img/good/goods3_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods3_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods3_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:4,
//						imgList:[{
//							index:1,
//							img:"img/good/goods4_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods4_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods4_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:5,
//						imgList:[{
//							index:1,
//							img:"img/good/goods5_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods5_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods5_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:6,
//						imgList:[{
//							index:1,
//							img:"img/good/goods6_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods6_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods6_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:7,
//						imgList:[{
//							index:1,
//							img:"img/good/goods7_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods7_2.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:8,
//						imgList:[{
//							index:1,
//							img:"img/good/goods8_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods8_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods8_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:9,
//						imgList:[{
//							index:1,
//							img:"img/good/goods9_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods9_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods9_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:10,
//						imgList:[{
//							index:1,
//							img:"img/good/goods10_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods10_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods10_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:11,
//						imgList:[{
//							index:1,
//							img:"img/good/goods11_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods11_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods11_3.jpg"
//						}],
//						imgWidth:28.571428571428573,
//						font:14
//					},{
//						goodsId:12,
//						imgList:[{
//							index:1,
//							img:"img/good/goods12_1.jpg"
//						},{
//							index:2,
//							img:"img/good/goods12_2.jpg"
//						},{
//							index:3,
//							img:"img/good/goods12_3.jpg"
//						}]
//					}],
//				imgWidth:28.571428571428573,
//				font:14,
//				index:i
//				});
//			}
//		}
//	});
	var goodslist2 = new GoodsList({
		renderTo:"goodsList2",
		dataSource:"selectAllGoods.action"
	});
});