window.onload = function(){
	var grid1 = new Grid({
		renderTo:"gridContainer1",
		dataSource:[{
			"id":"001",
			"name":"JMsolution韩国JM急救面膜水光炸弹超强深层补水玻尿酸保湿修复",
			"des":"全天猫实物商品通用",
			"img":"goods1_1.jpg",
			"price":98,
			"sales":50000,
			"stock":487510,
			"createDate":"2018-5-2"
		},{
			"id":"002",
			"name":"JMsolution韩国JM急救面膜水光炸弹超强深层补水玻尿酸保湿修复",
			"des":"全天猫实物商品通用",
			"img":"goods1_1.jpg",
			"price":98,
			"sales":50000,
			"stock":487510,
			"createDate":"2018-5-2"
		},{
			"id":"003",
			"name":"JMsolution韩国JM急救面膜水光炸弹超强深层补水玻尿酸保湿修复",
			"des":"全天猫实物商品通用",
			"img":"goods1_1.jpg",
			"price":98,
			"sales":50000,
			"stock":487510,
			"createDate":"2018-5-2"
		},{
			"id":"004",
			"name":"JMsolution韩国JM急救面膜水光炸弹超强深层补水玻尿酸保湿修复",
			"des":"全天猫实物商品通用",
			"img":"goods1_1.jpg",
			"price":98,
			"sales":50000,
			"stock":487510,
			"createDate":"2018-5-2"
		},{
			"id":"005",
			"name":"JMsolution韩国JM急救面膜水光炸弹超强深层补水玻尿酸保湿修复",
			"des":"全天猫实物商品通用",
			"img":"goods1_1.jpg",
			"price":98,
			"sales":50000,
			"stock":487510,
			"createDate":"2018-5-2"
		}],
		title:[{
			name:"id",
			alias:"商品编号"
		},{
			name:"name",
			alias:"商品名称"
		},{
			name:"des",
			alias:"描述信息"
		},{
			name:"img",
			alias:"商品图片"
		},{
			name:"price",
			alias:"价格"
		},{
			name:"sales",
			alias:"累计销售"
		},{
			name:"stock",
			alias:"剩余库存"
		},{
			name:"createDate",
			alias:"创建时间"
		}]
	});
	var grid2 = new Grid({
		renderTo:"gridContainer2",
		dataSource:"servlet/SelectAllGoods",
		title:[{
			name:"id",
			alias:"商品编号"
		},{
			name:"name",
			alias:"商品名称"
		},{
			name:"des",
			alias:"描述信息"
		},{
			name:"img",
			alias:"商品图片"
		},{
			name:"price",
			alias:"价格"
		},{
			name:"sales",
			alias:"累计销售"
		},{
			name:"stock",
			alias:"剩余库存"
		},{
			name:"createTime",
			alias:"创建时间"
		}]
	});
};

